parameters:
    allies_orobugsnag.handler.class:          Allies\Bundle\OroBugsnagBundle\Handler\BugsnagHandler
    
services:
    allies_orobugsnag.handler:
        class:      %allies_orobugsnag.handler.class%
        arguments:
            - @allies_orobugsnag.client
            - @oro_config.manager
            
    allies_orobugsnag.client:
        parent: bugsnag
        factory: ['@allies_orobugsnag.factory', make]
        
    allies_orobugsnag.factory:
        class:  %bugsnag.factory%
        arguments:
            - @bugsnag.resolver
            - null
            - null
            - '%bugsnag.api_key%'
            - '%bugsnag.endpoint%'
            - '%bugsnag.callbacks%'
            - '%bugsnag.user%'
            - '%bugsnag.app_type%'
            - '%bugsnag.app_version%'
            - '%bugsnag.batch_sending%'
            - '%bugsnag.hostname%'
            - '%bugsnag.send_code%'
            - '%bugsnag.strip_path%'
            - '%bugsnag.project_root%'
            - '%kernel.root_dir%'
            - '%kernel.environment%'
            - '%bugsnag.release_stage%'
            - '%bugsnag.notify_release_stages%'
            - '%bugsnag.filters%'